version: 2
jobs:
  build:
    working_directory: /tmp/mackerel-plugins
    docker:
      - image: golang:1.10.0
    steps:
       - checkout
       - run: GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o build/${CIRCLE_PROJECT_REPONAME}
